theme: jekyll-theme-architect
title: 'Building a Book in <span class="LaTeX">L<sup>a</sup>T<sub>e</sub>X</span>'
description: 'A tutorial for building a printable book in <span class="LaTeX">L<sup>a</sup>T<sub>e</sub>X</span>'
